@Plot_HostAddress = http://localhost:8085

// To use this as a testing area for the endpoints, note that
// most endpoints need an authentication token and the user
// needs certain roles to be able to execute some endpoints
// for the program. If the request doesn't have the authentication
// token in the bearer header or the user doesn't have the 
// permissions to do the endpoint, then the endpoint will
// send back a 401 unauthorized response. To send a request
// with the authentication header, you will need to send
// the login endpoint post request with correct permissions and
// the authentication token will be in the Set-Cookie header from
// the response. Copy, paste, and replace the
// <insert auth token here without angle brackets> with
// the token and hit the send request button above the endpoint request.
// Each request needs to be seperated by the ### comment line and
// the header for the authentication bearer token needs to be
//
// Authorization: Bearer exampletokenvalue
// 
// With the space afterwards.
// If you don't have a space, then it will not work because the 
// request will try to think that the body of the request is also
// apart of the token (It is weird and I spent way too long to figure that out)
// Example requests with authorization:
//
// ###
//
// GET {{Plot_HostAddress}}/api/users
// Accept: application/json
// Authorization: Bearer randomtokenvalue
//
// ###
// 
// ###
// POST {{Plot_HostAddress}}/api/auth/register
// Content-Type: application/json
// Accept: application/json
// Authorization: Bearer randomtokenvalue
//
// {
//    "Email": "jordan_houlihan@yahoo.com",
//    "Password": "pizzachips",
//    "FirstName": "Jordan",
//   "LastName": "Houlihan",
//    "Role": 1,
//    "Active": 1
// }
//
// ###
//

GET {{Plot_HostAddress}}/api/users/get-all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIlJvbGUiOiJNYW5hZ2VyIiwiVXNlcklkIjoiNDAiLCJuYmYiOjE3NDM3OTYwOTQsImV4cCI6MTc0MzgzOTI5NCwiaWF0IjoxNzQzNzk2MDk0LCJpc3MiOiJodHRwOi8vYmFja2VuZDo4MDg1LyIsImF1ZCI6Imh0dHA6Ly9mcm9udGVuZDo4MDgwLyJ9.eb7NRKrzpmBCXSlx-G-XpQK8V7qAg1EoRKPWFHAttuo

###

GET {{Plot_HostAddress}}/api/users/1
Accept: application/json

###

POST {{Plot_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "FirstName": "Bart",
    "LastName": "Simpson",
    "Email": "bartsimpson@gmail.com",
    "Role": 1,
    "Store": 1
}

###

POST {{Plot_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "Email": "admin@email.com",
    "Password": "admin25!"
}

###

POST {{Plot_HostAddress}}/api/auth/logout

###

POST {{Plot_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json
Authorization: Bearer <insert auth token here without angle brackets>

{
    "Email": "jordan_houlihan@yahoo.com",
    "Password": "pizzachips",
    "FirstName": "Jordan",
    "LastName": "Houlihan",
    "Role": 1,
    "Active": 1
}

###

POST {{Plot_HostAddress}}/api/auth/reset-password
Content-Type: application/json
Accept: application/json

{
    "NewPassword": "ILovePizza34",
    "token": "<insert auth token here without angle brackets>"
}

###

POST {{Plot_HostAddress}}/api/auth/password-reset-request
Content-Type: application/json
Accept: application/json

{
    "EmailAddress": "jordan_houlihan@yahoo.com"
}

###

GET {{Plot_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer <insert auth token here without angle brackets>

###

PATCH {{Plot_HostAddress}}/api/users/public-info/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer <insert auth token here without angle brackets>

{
    "FirstName": "",
    "LastName": ""
}

###

POST {{Plot_HostAddress}}/api/auth/test-password
Content-Type: application/json
Accept: application/json

###
GET {{Plot_HostAddress}}/api/stores/get-all
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIlJvbGUiOiJNYW5hZ2VyIiwiVXNlcklkIjoiNDAiLCJuYmYiOjE3NDM3OTc4NzYsImV4cCI6MTc0Mzg0MTA3NiwiaWF0IjoxNzQzNzk3ODc2LCJpc3MiOiJodHRwOi8vYmFja2VuZDo4MDg1LyIsImF1ZCI6Imh0dHA6Ly9mcm9udGVuZDo4MDgwLyJ9.xSmDZZXFndnyU4QRpIh45zJixiJOfA6nuFRJ9sJLpts

###
GET {{Plot_HostAddress}}/api/stores/access/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIlJvbGUiOiJNYW5hZ2VyIiwiVXNlcklkIjoiNDAiLCJuYmYiOjE3NDM3OTc4NzYsImV4cCI6MTc0Mzg0MTA3NiwiaWF0IjoxNzQzNzk3ODc2LCJpc3MiOiJodHRwOi8vYmFja2VuZDo4MDg1LyIsImF1ZCI6Imh0dHA6Ly9mcm9udGVuZDo4MDgwLyJ9.xSmDZZXFndnyU4QRpIh45zJixiJOfA6nuFRJ9sJLpts

###
POST {{Plot_HostAddress}}/api/stores
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Ik5pY2tMZWphQGVtYWlsLmNvbSIsIlJvbGUiOiJPd25lciIsIlVzZXJJZCI6IjEiLCJuYmYiOjE3NDM2MTc2MDUsImV4cCI6MTc0MzYyMTIwNSwiaWF0IjoxNzQzNjE3NjA1LCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDg1IiwiYXVkIjoiaHR0cDovLzAuMC4wLjA6ODA4MCJ9.nWl2ujpm5uc59E4ncKxUsuKqI3pfEMOkvMUBUjY2Uis

{
    "NAME":"Detroit Plato",
    "ADDRESS":"123 Main St.",
    "CITY": "Detroit",
    "STATE":"Michigan",
    "ZIP":"12345",
    "WIDTH":50,
    "HEIGHT":50,
}